<!--
<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
    <p><a class="btn btn-success btn-large" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Follow Development') ?></h2>
        <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Discover Modules') ?></h2>
        <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
        <p><a class="btn btn-success" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Help &amp; Support') ?></h2>
       <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
       <p><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
   </div>
</div>
-->
<div class="hero-unit">
    <p><a href="http://www.doctrine-project.org/projects/orm.html" target="_blank">http://www.doctrine-project.org/projects/orm.html</a>
    </p><p><a href="http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/getting-started.html" target="_blank">http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/getting-started.html</a>
    </p><p><a href="http://zend-framework-community.634137.n4.nabble.com/Doctrine-2-module-is-tight-to-MVC-td4659346.html" target="_blank">http://zend-framework-community.634137.n4.nabble.com/Doctrine-2-module-is-tight-to-MVC-td4659346.html</a>
    </p><p><a href="http://stackoverflow.com/questions/12712359/zend-soap-with-doctrine-2-1-problems-flush-soap-unknown-error" target="_blank">http://stackoverflow.com/questions/12712359/zend-soap-with-doctrine-2-1-problems-flush-soap-unknown-error</a>
    </p><p><a href="http://shaneauckland.co.uk/2012/11/setting-up-doctrine-with-zend-framework-2/" target="_blank">http://shaneauckland.co.uk/2012/11/setting-up-doctrine-with-zend-framework-2/</a>
    </p><p><a href="http://www.jasongrimes.org/2012/01/using-doctrine-2-in-zend-framework-2/" target="_blank">http://www.jasongrimes.org/2012/01/using-doctrine-2-in-zend-framework-2/</a>
    </p><p><a href="https://github.com/jasongrimes/zf2tutorial/blob/master/module/Album/config/module.config.php" target="_blank">https://github.com/jasongrimes/zf2tutorial/blob/master/module/Album/config/module.config.php</a>
    </p><p><a href="http://framework.zend.com/manual/1.12/en/zend.soap.server.html" target="_blank">http://framework.zend.com/manual/1.12/en/zend.soap.server.html</a>
    </p><p><a href="http://www.ibm.com/developerworks/library/x-zsoap/" target="_blank">http://www.ibm.com/developerworks/library/x-zsoap/</a>
    </p><p><a href="http://stackoverflow.com/questions/13575589/zend-framework-2-soap-not-compatible-with-net" target="_blank">http://stackoverflow.com/questions/13575589/zend-framework-2-soap-not-compatible-with-net</a>
    </p><p><a href="http://framework.zend.com/manual/2.1/en/tutorials/unittesting.html" target="_blank">http://framework.zend.com/manual/2.1/en/tutorials/unittesting.html</a>
    </p><p><a href="http://stackoverflow.com/questions/12937546/how-to-setup-first-application-in-zend-framework-2" target="_blank">http://stackoverflow.com/questions/12937546/how-to-setup-first-application-in-zend-framework-2</a>
    </p><p><a href="http://samminds.com/2012/07/zend-framework-2-installation-on-xampp-for-windows/" target="_blank">http://samminds.com/2012/07/zend-framework-2-installation-on-xampp-for-windows/</a>
    </p><p><a href="http://samminds.com/2013/04/understanding-zf2-configuration/" target="_blank">http://samminds.com/2013/04/understanding-zf2-configuration/</a>
    </p><p><a href="http://samminds.com/2013/03/zfcuser-bjyauthorize-and-doctrine-working-together/" target="_blank">http://samminds.com/2013/03/zfcuser-bjyauthorize-and-doctrine-working-together/</a>
    </p><p><a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">https://github.com/zendframework/ZendSkeletonApplication</a>
        </p>
</div>

